![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/68501079-0695df00-023c-11ea-841f-455dac84a089.jpg"
    style="width:400px; float: right; margin: 0 40px 40px 40px;"></img>

# Reading HTML tables

In this lecture we'll learn how to read and parse HTML tables from websites into a list of `DataFrame` objects to work with.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [1]:
!pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (4.2.6)

In [2]:
import pandas as pd

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

##Â Parsing raw HTML strings

Another useful pandas method is `read_html()`. This method will read HTML tables from a given URL, a file-like object, or a raw string containing HTML, and return a list of `DataFrame` objects.

Let's try to read the following `html_string` into a `DataFrame`.

In [3]:
html_string = """
<table>
    <thead>
      <tr>
        <th>Order date</th>
        <th>Region</th> 
        <th>Item</th>
        <th>Units</th>
        <th>Unit cost</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1/6/2018</td>
        <td>East</td> 
        <td>Pencil</td>
        <td>95</td>
        <td>1.99</td>
      </tr>
      <tr>
        <td>1/23/2018</td>
        <td>Central</td> 
        <td>Binder</td>
        <td>50</td>
        <td>19.99</td>
      </tr>
      <tr>
        <td>2/9/2018</td>
        <td>Central</td> 
        <td>Pencil</td>
        <td>36</td>
        <td>4.99</td>
      </tr>
      <tr>
        <td>3/15/2018</td>
        <td>West</td> 
        <td>Pen</td>
        <td>27</td>
        <td>19.99</td>
      </tr>
    </tbody>
</table>
"""

In [4]:
dfs = pd.read_html(html_string)

The `read_html` just returned one `DataFrame` object:

In [5]:
len(dfs)

1

In [6]:
df = dfs[0]

df

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

Previous `DataFrame` looks quite similar to the raw HTML table, but now we have a `DataFrame` object, so we can apply any pandas operation we want to it.

In [7]:
df.shape

(4, 5)

In [8]:
df.loc[df['Region'] == 'Central']

  Order date   Region    Item  Units  Unit cost
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

In [9]:
df.loc[df['Units'] > 35]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

###Â Defining header

Pandas will automatically find the header to use thanks to the <thead> tag.
    
But in many cases we'll find wrong or incomplete tables that make the `read_html` method parse the tables in a wrong way without the proper headers.

To fix them we can use the `header` parameter.

In [10]:
html_string = """
<table>
  <tr>
    <td>Order date</td>
    <td>Region</td> 
    <td>Item</td>
    <td>Units</td>
    <td>Unit cost</td>
  </tr>
  <tr>
    <td>1/6/2018</td>
    <td>East</td> 
    <td>Pencil</td>
    <td>95</td>
    <td>1.99</td>
  </tr>
  <tr>
    <td>1/23/2018</td>
    <td>Central</td> 
    <td>Binder</td>
    <td>50</td>
    <td>19.99</td>
  </tr>
  <tr>
    <td>2/9/2018</td>
    <td>Central</td> 
    <td>Pencil</td>
    <td>36</td>
    <td>4.99</td>
  </tr>
  <tr>
    <td>3/15/2018</td>
    <td>West</td> 
    <td>Pen</td>
    <td>27</td>
    <td>19.99</td>
  </tr>
</table>
"""

In [11]:
pd.read_html(html_string)[0]

            0        1       2      3          4
0  Order date   Region    Item  Units  Unit cost
1    1/6/2018     East  Pencil     95       1.99
2   1/23/2018  Central  Binder     50      19.99
3    2/9/2018  Central  Pencil     36       4.99
4   3/15/2018     West     Pen     27      19.99

In this case, we'll need to pass the row number to use as header using the `header` parameter.

In [12]:
pd.read_html(html_string, header=0)[0]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

##Â Parsing HTML tables from the web

Now that we know how `read_html` works, go one step beyond and try to parse HTML tables directly from an URL.

To do that we'll call the `read_html` method with an URL as paramter.

### Simple example

In [13]:
html_url = "https://www.basketball-reference.com/leagues/NBA_2019_per_game.html"

In [14]:
nba_tables = pd.read_html(html_url)

In [15]:
len(nba_tables)

1

We'll work with the only one table found:

In [16]:
nba = nba_tables[0]

In [17]:
nba.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Ãlex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [32]:
nba.head(25)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Ãlex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
5,6,Deng Adel,SF,21,CLE,19,3,10.2,0.6,1.9,...,1.000,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,1.7
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,0,3.1,0.4,1.4,...,.500,0.1,0.4,0.6,0.9,0.3,0.0,0.3,0.6,1.0
7,8,LaMarcus Aldridge,C,33,SAS,81,81,33.2,8.4,16.3,...,.847,3.1,6.1,9.2,2.4,0.5,1.3,1.8,2.2,21.3
8,9,Rawle Alkins,SG,21,CHI,10,1,12.0,1.3,3.9,...,.667,1.1,1.5,2.6,1.3,0.1,0.0,0.8,0.7,3.7
9,10,Grayson Allen,SG,23,UTA,38,2,10.9,1.8,4.7,...,.750,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6
10,11,Jarrett Allen,C,20,BRK,80,80,26.2,4.2,7.1,...,.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
11,12,Kadeem Allen,PG,26,NYK,19,1,21.9,3.4,7.4,...,.778,0.4,2.3,2.7,4.0,0.8,0.2,1.4,2.4,9.9
12,13,Al-Farouq Aminu,PF,28,POR,81,81,28.3,3.2,7.3,...,.867,1.4,6.1,7.5,1.3,0.8,0.4,0.9,1.8,9.4
13,14,Justin Anderson,SF,25,ATL,48,4,9.6,1.3,3.3,...,.743,0.5,1.3,1.8,0.5,0.5,0.3,0.5,1.0,3.7
14,15,Kyle Anderson,SF,25,MEM,43,40,29.8,3.5,6.4,...,.578,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0
15,16,Ryan Anderson,PF,30,TOT,25,8,12.9,0.8,2.8,...,.750,0.7,1.4,2.2,0.8,0.2,0.0,0.6,1.0,2.5
16,16,Ryan Anderson,PF,30,PHO,15,8,18.5,1.3,4.0,...,.786,0.9,2.1,3.0,1.1,0.2,0.1,0.8,1.5,3.7
17,16,Ryan Anderson,PF,30,MIA,10,0,4.4,0.2,0.9,...,.500,0.4,0.5,0.9,0.2,0.1,0.0,0.2,0.2,0.7
18,17,Ike Anigbogu,C,20,IND,3,0,2.0,0.0,1.0,...,NaN,0.3,0.7,1.0,0.3,0.0,0.3,0.3,0.0,0.0
19,18,Giannis Antetokounmpo,PF,24,MIL,72,72,32.8,10.0,17.3,...,.729,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7
20,19,Kostas Antetokounmpo,PF,21,DAL,2,0,5.5,0.0,1.5,...,.500,0.0,0.5,0.5,0.0,1.0,0.0,0.5,0.0,1.0
21,20,Carmelo Anthony,PF,34,HOU,10,2,29.4,4.9,12.1,...,.682,0.9,4.5,5.4,0.5,0.4,0.7,0.8,3.2,13.4
22,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
23,21,OG Anunoby,SF,21,TOR,67,6,20.2,2.7,6.0,...,.581,0.9,2.1,2.9,0.7,0.7,0.3,0.8,2.1,7.0
24,22,Ryan Arcidiacono,PG,24,CHI,81,32,24.2,2.3,5.2,...,.873,0.3,2.4,2.7,3.3,0.8,0.0,0.8,2.1,6.7

In [39]:
 nba.drop(range(22, df.shape[0] + 1,20))

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Ãlex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,528,Tyler Zeller,C,29,MEM,4,1,20.5,4.0,7.0,...,.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
730,529,Ante Å½iÅ¾iÄ,C,22,CLE,59,25,18.3,3.1,5.6,...,.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
731,530,Ivica Zubac,C,21,TOT,59,37,17.6,3.6,6.4,...,.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
732,530,Ivica Zubac,C,21,LAL,33,12,15.6,3.4,5.8,...,.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
733,530,Ivica Zubac,C,21,LAC,26,25,20.2,3.8,7.2,...,.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

In [40]:
nba.head(25)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Ãlex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
5,6,Deng Adel,SF,21,CLE,19,3,10.2,0.6,1.9,...,1.000,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,1.7
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,0,3.1,0.4,1.4,...,.500,0.1,0.4,0.6,0.9,0.3,0.0,0.3,0.6,1.0
7,8,LaMarcus Aldridge,C,33,SAS,81,81,33.2,8.4,16.3,...,.847,3.1,6.1,9.2,2.4,0.5,1.3,1.8,2.2,21.3
8,9,Rawle Alkins,SG,21,CHI,10,1,12.0,1.3,3.9,...,.667,1.1,1.5,2.6,1.3,0.1,0.0,0.8,0.7,3.7
9,10,Grayson Allen,SG,23,UTA,38,2,10.9,1.8,4.7,...,.750,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6
10,11,Jarrett Allen,C,20,BRK,80,80,26.2,4.2,7.1,...,.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
11,12,Kadeem Allen,PG,26,NYK,19,1,21.9,3.4,7.4,...,.778,0.4,2.3,2.7,4.0,0.8,0.2,1.4,2.4,9.9
12,13,Al-Farouq Aminu,PF,28,POR,81,81,28.3,3.2,7.3,...,.867,1.4,6.1,7.5,1.3,0.8,0.4,0.9,1.8,9.4
13,14,Justin Anderson,SF,25,ATL,48,4,9.6,1.3,3.3,...,.743,0.5,1.3,1.8,0.5,0.5,0.3,0.5,1.0,3.7
14,15,Kyle Anderson,SF,25,MEM,43,40,29.8,3.5,6.4,...,.578,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0
15,16,Ryan Anderson,PF,30,TOT,25,8,12.9,0.8,2.8,...,.750,0.7,1.4,2.2,0.8,0.2,0.0,0.6,1.0,2.5
16,16,Ryan Anderson,PF,30,PHO,15,8,18.5,1.3,4.0,...,.786,0.9,2.1,3.0,1.1,0.2,0.1,0.8,1.5,3.7
17,16,Ryan Anderson,PF,30,MIA,10,0,4.4,0.2,0.9,...,.500,0.4,0.5,0.9,0.2,0.1,0.0,0.2,0.2,0.7
18,17,Ike Anigbogu,C,20,IND,3,0,2.0,0.0,1.0,...,NaN,0.3,0.7,1.0,0.3,0.0,0.3,0.3,0.0,0.0
19,18,Giannis Antetokounmpo,PF,24,MIL,72,72,32.8,10.0,17.3,...,.729,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7
20,19,Kostas Antetokounmpo,PF,21,DAL,2,0,5.5,0.0,1.5,...,.500,0.0,0.5,0.5,0.0,1.0,0.0,0.5,0.0,1.0
21,20,Carmelo Anthony,PF,34,HOU,10,2,29.4,4.9,12.1,...,.682,0.9,4.5,5.4,0.5,0.4,0.7,0.8,3.2,13.4
22,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
23,21,OG Anunoby,SF,21,TOR,67,6,20.2,2.7,6.0,...,.581,0.9,2.1,2.9,0.7,0.7,0.3,0.8,2.1,7.0
24,22,Ryan Arcidiacono,PG,24,CHI,81,32,24.2,2.3,5.2,...,.873,0.3,2.4,2.7,3.3,0.8,0.0,0.8,2.1,6.7

### Complex example

We can also use the `requests` module to get HTML code from an URL to parse it into `DataFrame` objects.

If we look at the given URL we can see multiple tables about The Simpsons TV show.

We want to keep the table with information about each season.

In [18]:
import requests

html_url = "https://en.wikipedia.org/wiki/The_Simpsons"

In [19]:
r = requests.get(html_url)

wiki_tables = pd.read_html(r.text, header=0)

In [20]:
len(wiki_tables)

41

In [21]:
simpsons = wiki_tables[1]

In [22]:
simpsons.head()

,Season,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
0,Season,Season,No. ofepisodes,Season premiere,Season finale,Time slot (ET),Avg. viewers(in millions),Most watched episode,Most watched episode
1,Season,Season,No. ofepisodes,Season premiere,Season finale,Time slot (ET),Avg. viewers(in millions),Viewers(millions),Episode title
2,1,1989â90,13,"December 17, 1989","May 13, 1990",Sunday 8:30Â pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990â91,22,"October 11, 1990","July 11, 1991",Thursday 8:00Â pm,24.4,33.6,"""Bart Gets an 'F'"""
4,3,1991â92,24,"September 19, 1991","August 27, 1992",Thursday 8:00Â pm,21.8,25.5,"""Colonel Homer"""

Quick clean on the table: remove extra header rows and set `Season` as index.

In [23]:
simpsons.drop([0, 1], inplace=True)

In [24]:
simpsons.set_index('Season', inplace=True)

Which season has the lowest number of episodes?

In [25]:
simpsons['No. ofepisodes'].unique()

array(['13', '22', '24', '25', '23', '21', '20'], dtype=object)

In [26]:
simpsons = simpsons.loc[simpsons['No. ofepisodes'] != 'TBA']

In [27]:
min_season = simpsons['No. ofepisodes'].min()

min_season

'13'

In [28]:
simpsons.loc[simpsons['No. ofepisodes'] == min_season]

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989â90,13,"December 17, 1989","May 13, 1990",Sunday 8:30Â pm,27.8,33.5,"""Life on the Fast Lane"""

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

##Â Save to CSV file

Finally save the `DataFrame` to a CSV file as we saw on previous lectures.

In [29]:
simpsons.head()

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989â90,13,"December 17, 1989","May 13, 1990",Sunday 8:30Â pm,27.8,33.5,"""Life on the Fast Lane"""
2,1990â91,22,"October 11, 1990","July 11, 1991",Thursday 8:00Â pm,24.4,33.6,"""Bart Gets an 'F'"""
3,1991â92,24,"September 19, 1991","August 27, 1992",Thursday 8:00Â pm,21.8,25.5,"""Colonel Homer"""
4,1992â93,22,"September 24, 1992","May 13, 1993",Thursday 8:00Â pm,22.4,28.6,"""Lisa's First Word"""
5,1993â94,22,"September 30, 1993","May 19, 1994",Thursday 8:00Â pm,18.9,24.0,"""Treehouse of Horror IV"""

In [30]:
simpsons.to_csv('out.csv')

In [31]:
pd.read_csv('out.csv', index_col='Season').head()

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989â90,13,"December 17, 1989","May 13, 1990",Sunday 8:30Â pm,27.8,33.5,"""Life on the Fast Lane"""
2,1990â91,22,"October 11, 1990","July 11, 1991",Thursday 8:00Â pm,24.4,33.6,"""Bart Gets an 'F'"""
3,1991â92,24,"September 19, 1991","August 27, 1992",Thursday 8:00Â pm,21.8,25.5,"""Colonel Homer"""
4,1992â93,22,"September 24, 1992","May 13, 1993",Thursday 8:00Â pm,22.4,28.6,"""Lisa's First Word"""
5,1993â94,22,"September 30, 1993","May 19, 1994",Thursday 8:00Â pm,18.9,24.0,"""Treehouse of Horror IV"""

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)